apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-metricbeat-role-binding
  labels:
    app: "release-name-metricbeat"
    chart: "metricbeat-7.17.3"
    heritage: "Helm"
    release: "release-name"
roleRef:
  kind: ClusterRole
  name: release-name-metricbeat-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: release-name-metricbeat
  namespace: metricbeat
