apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-metricbeat-role
  labels:
    app: "release-name-metricbeat"
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: ["get", "create", "update"]
