apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-filebeat-role-binding
  labels:
    app: "release-name-filebeat"
    chart: "filebeat-7.17.3"
    heritage: "Helm"
    release: "release-name"
roleRef:
  kind: Role
  name: release-name-filebeat-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: release-name-filebeat
  namespace: filebeat
