apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-filebeat
  annotations:
  labels:
    app: "release-name-filebeat"
    chart: "filebeat-7.17.3"
    heritage: "Helm"
    release: "release-name"
