apiVersion: v1
kind: Secret
metadata:
  name: release-name-minio
  labels:
    app: minio
    chart: minio-5.0.32
    release: release-name
    heritage: Helm
type: Opaque
data:
  accesskey: "QUtJQUlPU0ZPRE5ON0VYQU1QTEU="
  secretkey: "cGFzc3dvcmQ="
